#!/bin/bash
#
# Linux Shell Scripting Tutorial 1.05r3, Summer-2002
#
# Written by Vivek G. Gite <vivek@nixcraft.com>
#
# Latest version can be found at http://www.nixcraft.com/
#
# Q19
#

nouser=`who | wc -l`
echo -e "User name: $USER (Login name: $LOGNAME)" 
echo -e "Current Shell: $SHELL"  
echo -e "Home Directory: $HOME" 
echo -e "Your O/s Type: $OSTYPE" 
echo -e "PATH: $PATH" 
echo -e "Current directory: `pwd`" 
echo -e "Currently Logged: $nouser user(s)" 
